### ISSUE TITLE
Order book

### ISSUE THREAD

**Issue by jambudipa** [yeikiu/ts-kraken#14]
Hey Yeikiu

Was looking for a node implementation of the signature generator for private REST methods for Kraken, and came across your library. It's much better than my implementation, but it is missing the ws order book stream.

Was thinking of adding that and creating a PR, would you into that? Otherwise I'll just pull the repo and add the code directly to my app with the augmentation.

Mark

**Comment by jambudipa** [comment]
Decided to fork it instead

**Comment by yeikiu** [comment]
Hey @jambudipa!

Glad you find the lib useful. I'd be more than happy to merge your PR if you want to contribute 😃

**Comment by jambudipa** [comment]
Ok, just tweaking it at the moment 👍

**Comment by yeikiu** [comment]
Added under v3.0.24

https://github.com/yeikiu/ts-kraken/releases/tag/v3.0.24
